### ISSUE TITLE
面向不懂代码的医学生的一份从零安装指南 ( A Fool Tutorial for those who have trouble configuring this program)

### ISSUE THREAD

**Issue by lxx2013** [jackyko1991/Vessel-Centerline-Extraction#2]
>Today I install this program on my Ubuntu with a lot of difficulties. Now I share the steps for green-hands.

## 1. 安装 ubuntu
   - 百度下载 vmware workstation 最新版
   - 网易镜像下载 [ubuntu 14.04.5](https://mirrors.163.com/ubuntu-releases/14.04.5/ubuntu-14.04.5-desktop-amd64.iso)
    - 在 vmware 中安装 ubuntu
    - 之后 `apt-get install`可能会遇到访问外网网速慢的问题,可以修改阿里云源, [参考链接](https://www.cnblogs.com/littlemonsters/p/5783690.html)

## 2.安装 cmake
在[cmake 官网](https://cmake.org/download/)下载最新版 cmake 压缩包[cmake-3.12.2.tar.gz](https://cmake.org/files/v3.12/cmake-3.12.2.tar.gz)
解压至 Download 文件夹
![](https://upload-images.jianshu.io/upload_images/2591556-f81a3bcb963fc56b.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
其中宿主机(win 或 mac) 可以和 vmware 无缝拷贝文件

## 3. ubuntu 装一些软件包(要查找 Terminal 应用并锁定在左边 dock 栏)
`sudo apt-get install g++` 安装支持c++11的g++ 4.8.4
`sudo apt-get install vim` vim 是代码编辑器
`cd cmake-3.12.2` 其中 cd 的意思是`进入指定文件夹`
`./bootstrap --prefix=/usr/local/cmake/`  先执行配置
![](https://upload-images.jianshu.io/upload_images/2591556-7c283a16726a853d.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
配置成功的话就可以开始安装了(不成功的话拿着报错信息去 google) . *csdn 博客基本都是复读机参考价值比较有限*
`make`
`sudo make install`
##4. 如果上一步安装成功了,cmake 还没办法立即使用,需要把它加入环境变量
`sudo vim /etc/profile`
然后按大写字母 `G` 转到最后一行, 按键盘上的`i`进入输入模式,输入
```
#cmake 
export PATH=$PATH:/usr/local/cmake/bin
```
然后按`ESC`键,输入`wq!`再 `enter`即保存成功.
>这就是 vim 的编辑方式, `vim xxx.file` => `insert some words` => `wq!`退出

修改完`PATH`这个环境变量后还需要让他立即生效, 执行
```
source /etc/profile
cmake --version
```
成功输出版本号则 cmake 安装成功
以后什么时候提示找不到 cmake的话就再执行一次
`source /etc/profile`

## 5. 安装 python 依赖包(等会 VMTK 要用)
`python --version`可以看到 ubuntu14.04.5自带 python2.7
接下来安装
```bash
sudo apt-get install python-dev libqt4-dev
sudo mkdir /usr/lib/python2.7/config/
sudo cp /usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so /usr/lib/python2.7/config/libpython2.7.so
```
## 6.开始着手安装 VMTK (基本是按照[官网](http://www.vmtk.org/download/)流程)
```
sudo apt-get install git
cd ~/Downloads
git clone https://github.com/vmtk/vmtk.git
sudo apt-get install libxt-dev libgl1-mesa-glx libgl1-mesa-dev libglapi-mesa libosmesa-dev build-essential
mkdir vmtk-build
cd vmtk-build

cmake ../vmtk -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/python2.7/config/libpython2.7.so 

make -j2  #这一步会很慢, -j2已经是双核加速了 视不同机器而定可能还是还是要很久
```

## 7. 执行 Vessel 程序
```
cd ~/Downloads
git clone https://github.com/jackyko1991/Vessel-Centerline-Extraction.git
cd Vessel-Centerline-Extraction
vim CMakeList.txt
```
按 `i` 进入编辑模式,需要修改如下三行红色字符串部分:
![](https://upload-images.jianshu.io/upload_images/2591556-8544b40d1b0948b8.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
注意我的用户名是 `lxx` 所以路径是`/home/lxx` ,你的用户名是 x 的话就是`/home/x/Downloads/vmtk-build/VMTK-Build`,共需修改3行, 改好后`:wq!`保存退出
```
cmake .
make
./CenterlineExtraction  test_data/left/lumen.stl
```
**成功输出血管图像!**
![](https://upload-images.jianshu.io/upload_images/2591556-b882ec163e813a52.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by jackyko1991** [comment]
其實在windows 上可以直接使用，過兩天我比較有空可以寫一個windows 版本的build from source 教程跟一套windows
10 可以直接用的exe 軟件

在 2018年9月10日週一 22:06，Xinxing Li <notifications@github.com> 寫道：
