### ISSUE TITLE
Voronoi diagram 输出显示

### ISSUE THREAD

**Issue by junqiangchen** [jackyko1991/Vessel-Centerline-Extraction#5]
作者你好，分享的项目非常棒，我下了你的代码也测试了一下，可以做中心线提取，因为中心线是根据每个位置的最小内接球来确定的，我想将最小内结球的Voronoi diagram显示出来，我尝试在Centerlin.cpp文件中的CalculateCenterline（）函数里加了centerlinesFilter->SetGenerateVoronoiDiagram(m_appendEndPointsFlag);但是结果没有什么变化，不知道作者知道在哪里修改或添加函数功能可以实现呢？
非常感谢

**Comment by jackyko1991** [comment]
如果你想直接在程序中顯示voronoi diagram,你需要在[interactorStyleCenterline](https://github.com/jackyko1991/Vessel-Centerline-Extraction/blob/master/interactorStyleCenterline.cpp)中增加voronoi的actor.同時需在main.cpp中新增vornoi diagram的actor,類似以下的:

```cpp
vtkSmartPointer<vtkPolyDataMapper> centerlineMapper = vtkSmartPointer<vtkPolyDataMapper>::New();
centerlineMapper->SetInputData(centerline);
vtkSmartPointer<vtkActor> centerlineActor = vtkSmartPointer<vtkActor>::New();
centerlineActor->SetMapper(centerlineMapper);
```

我沒有直接處理過voronoi diagram,建議先利用paraview看使用了SetGenerateVoronoiDiagram(m_appendEndPointsFlag) 的輸出有沒有正確生成後才開始修改代碼

**Comment by jackyko1991** [comment]
具體生成voronoi diagram可以參考[source code](https://github.com/vmtk/vmtk/blob/master/vmtkScripts/vmtkcenterlines.py)的使用方法
```python
if (self.VoronoiDiagram is not None) and (self.PoleIds is not None):
            centerlineFilter.GenerateVoronoiDiagramOff()
            centerlineFilter.SetVoronoiDiagram(self.VoronoiDiagram)
            centerlineFilter.SetPoleIds(self.PoleIds)
```

```python
self.VoronoiDiagram = centerlineFilter.GetVoronoiDiagram()
```

**Comment by junqiangchen** [comment]
非常感谢作者你的回答，按照你提供的参考资料，我在你的代码基础上进行了修改：
vtkSmartPointer<vtkvmtkPolyDataCenterlines> centerlinesFilter = vtkSmartPointer<vtkvmtkPolyDataCenterlines>::New();
	centerlinesFilter->SetInputData(m_cappedSurface);
	centerlinesFilter->SetSourceSeedIds(m_sourceIds);
	centerlinesFilter->SetTargetSeedIds(m_targetIds);
	centerlinesFilter->SetAppendEndPointsToCenterlines(m_appendEndPointsFlag);
	centerlinesFilter->SetSimplifyVoronoi(0);
	centerlinesFilter->GenerateVoronoiDiagramOn();
	centerlinesFilter->SetRadiusArrayName("Radius");
	centerlinesFilter->SetEdgeArrayName("Edge");
	centerlinesFilter->SetEdgePCoordArrayName("PCoord");
	centerlinesFilter->Update();

	m_centerline->DeepCopy(centerlinesFilter->GetOutput());
	m_voronoidiagram = centerlinesFilter->GetVoronoiDiagram();
我测试输出m_voronoidiagram是非空的。在ExtractCenterline函数中添加代码如下：
vtkSmartPointer<vtkPolyDataMapper> voronoidiagramMapper = vtkSmartPointer<vtkPolyDataMapper>::New();
			voronoidiagramMapper->SetInputData(VoronoiDiagram);
			vtkSmartPointer<vtkActor> voronoidiagramActor = vtkSmartPointer<vtkActor>::New();
			voronoidiagramActor->SetMapper(voronoidiagramMapper);

			// put the actor into render window
			vtkSmartPointer<vtkRenderer> ren = vtkSmartPointer<vtkRenderer>::New();
			ren->AddActor(surfaceActor);
			ren->AddActor(centerlineActor);
			ren->AddActor(voronoidiagramActor);
最后将结果写成vtp形式，用paraview来看的时候，没有任何结果。
